import "../styles/globals.css";

import type { Metadata } from "next";
import GearProvider from "@/lib/providers/gear";
import { LayoutProps } from "@/interface";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body >
        <GearProvider>
          {children}
        </GearProvider>
      </body>
    </html>
  );
}
